name: Publish

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build files
        run: ./gradlew build

      - name: Publish to API
        run: ./gradlew publish
        env:
          repository_username: ${{ secrets.REPOSITORY_USERNAME }}
          repository_password: ${{ secrets.REPOSITORY_PASSWORD }}